### ISSUE TITLE
MessageClient的Subscribe与Unsubscribe方法返回错误的状态

### ISSUE THREAD

**Issue by zxgamekingdom** [yswenli/SAEA#11]
与MessageServer对象同一个程序集的MessageClient对象在第一次调用Subscribe方式会返回false,之后再多次调用会返回true.
与MessageServer对象不在同一个程序集的MessageClient对象无论如何调用Subscribe返回的都是false,但可以接受到消息.
Unsubscribe也会出现上述的情况.

**Comment by zxgamekingdom** [comment]
使用的SAEA.Sockets与SAEA.MessageSocket都是5.1.7.6,从Nuget导入的.WIN10 X64 1903,VS2019,.NET Core SDK 3.0.100

**Comment by yswenli** [comment]
谢谢反馈~
