### ISSUE TITLE
偶发性异常

### ISSUE THREAD

**Issue by fp0991** [yswenli/SAEA#13]
说明: 由于未经处理的异常，进程终止。
异常信息: System.NullReferenceException
   在 SAEA.Sockets.Core.Tcp.IocpServerSocket.ProcessSended(System.Net.Sockets.SocketAsyncEventArgs)
   在 SAEA.Sockets.Core.Tcp.IocpServerSocket.IO_Completed(System.Object, System.Net.Sockets.SocketAsyncEventArgs)
   在 System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(System.Net.Sockets.SocketAsyncEventArgs)
   在 System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(System.Object)
   在 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   在 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   在 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   在 System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncFailure(System.Net.Sockets.SocketError, Int32, System.Net.Sockets.SocketFlags)
   在 System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
   在 System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)

网络状况不佳的情况下偶发性出现此异常，无法在我自己的代码中拦截这个异常，从而会导致程序崩溃

**Comment by fp0991** [comment]
同样在网络状况不佳的情况下，还会出现一个异常，同样无法拦截

说明: 由于未经处理的异常，进程终止。
异常信息: System.InvalidOperationException
   在 System.Net.Sockets.SocketAsyncEventArgs.StartConfiguring()
   在 System.Net.Sockets.SocketAsyncEventArgs.SetBufferInternal(Byte[], Int32, Int32)
   在 SAEA.Sockets.Core.BufferManager.FreeBuffer(System.Net.Sockets.SocketAsyncEventArgs)
   在 SAEA.Sockets.Core.SessionManager.Free(SAEA.Sockets.Interface.IUserToken)
   在 SAEA.Sockets.Core.Tcp.IocpServerSocket.Disconnect(SAEA.Sockets.Interface.IUserToken, System.Exception)
   在 SAEA.Sockets.Core.Tcp.IocpServerSocket._sessionManager_OnTimeOut(SAEA.Sockets.Interface.IUserToken)
   在 SAEA.Sockets.Core.SessionManager.<.ctor>b__11_0()
   在 SAEA.Common.ThreadHelper+<>c__DisplayClass2_0.<PulseAction>b__0()
   在 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   在 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   在 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   在 System.Threading.ThreadHelper.ThreadStart()

**Comment by yswenli** [comment]
收到反馈，会在下个版本中处理
