### ISSUE TITLE
关于 SocketAsyncEventArgs 为什么要单独设计一个池子？

### ISSUE THREAD

**Issue by XCStar** [yswenli/SAEA#15]
userToken已经有个池子了，为什么不直接给usertoken初始化一个读的SocketAsyncEventArgs和写的SocketAsyncEventArgs对象，而要单独用个 SocketAsyncEventArgsPool，也没看到哪里单独需要取SocketAsyncEventArgs 而不经过userToken,设计一个池子是不是多此一举？

**Comment by yswenli** [comment]
iocp的核心思想就是要复用，其中复用SocketAsyncEventArgs非常重要~
另外用一个大池子肯定比两个小池子要节省资源~
最后你没有看到的地方请仔细看~
