### ISSUE TITLE
how to specify the ip:port for mqtt broker?

### ISSUE THREAD

**Issue by danielstock** [yswenli/SAEA#16]
i wrote a mqtt server example according to the following article:
https://github.com/yswenli/SAEA/blob/master/Src/SAEA.MQTTTest/ServerTest.cs

and after the server started, i used a mqtt.fx client to connect to the server.
but i did not know which port to connect to.

thanks.

**Comment by yswenli** [comment]
DefaultEndpointPort(int value = 1883)
