### ISSUE TITLE
你好，我仅仅是实例化一个Server之后，程序就多了700+M的内存

### ISSUE THREAD

**Issue by qzwzqty** [yswenli/SAEA#2]

**Comment by yswenli** [comment]
注意初始化的buffer大小和连接数的设定~另外700M不算大~

**Comment by qzwzqty** [comment]
你好。。我把连接数改成 100 就没这么大了。我主要是做unity与wpf之间通讯，用Socket，所以700M很大了。。我之前以为MessageServer里的count是最大连接数。。谢了
