### ISSUE TITLE
如何与Netty一起工作？

### ISSUE THREAD

**Issue by guopenglun** [yswenli/SAEA#3]
例如：
在Linux 上的netty 作为服务端
Windows客户端选用这个库作为通信手段
但是我看到的示例里都是自己把服务端和客户端的活都干了。
我不确定这个库是否能和其他库完美协作，
请问您有没有测试或者考虑过我上面说到的情况？

**Comment by yswenli** [comment]
这个上面的示例表示的是各种场景的使用，和其他客户端服务器使用什么没有关系；
比如SAEA.Http作为服务器，其他浏览器作为客户端
又或者SAEA.RedisSocket作为客户端，redis作为服务器
如何与netty一起工作，这个你只需要考虑你所对接的nettty协议就可以了~

**Comment by guopenglun** [comment]
谢谢您的回复。
