### ISSUE TITLE
IocpClientSocket.ConnectAsync 当连接不上，callBack 没有执行！

### ISSUE THREAD

**Issue by cmwong** [yswenli/SAEA#8]
你好，
当连接不上，callBack 没有执行！
SAEA.Sockets.Core.Tcp.IocpClientSocket.ConnectAsync(Action<SocketError> callBack = null)

可否把 void ProcessConnected(SocketAsyncEventArgs e) 里调用
_connectCallBack?.Invoke(e.SocketError);
移到 if(Connected) 外去。这里造成只在 Connected 才会调用 callBack。

**Comment by cmwong** [comment]
你好，

version 5.1.7.5
Unhandled Exception: SAEA.Sockets.Model.KernelException: connection failed!

https://github.com/yswenli/SAEA/blob/2f0c986dfe525b414b8c57ec9e271cf47ecea516/Src/SAEA.Sockets/Core/Tcp/IocpClientSocket.cs#L188

我该如何补抓这个 KernalException?


这是我要用 IocpClientSocket 的代码
[https://github.com/cmwong/LearnSuperSocket/blob/master/SocketServer/SAEASocket/EventSocketClient.cs](url)

这是测试代码。
https://github.com/cmwong/LearnSuperSocket/tree/master/SocketServer/testSAEASocket1

**Comment by yswenli** [comment]
谢谢你，这是一bug，后续我会修复这个~



------------------ 原始邮件 ------------------
发件人: "cmwong"<notifications@github.com>; 
发送时间: 2019年9月27日(星期五) 晚上11:02
收件人: "yswenli/SAEA"<SAEA@noreply.github.com>; 
抄送: "WALL·E"<wenguoli_520@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [yswenli/SAEA] IocpClientSocket.ConnectAsync 当连接不上，callBack 没有执行！ (#8)




你好，
 
version 5.1.7.5
 Unhandled Exception: SAEA.Sockets.Model.KernelException: connection failed!
 
https://github.com/yswenli/SAEA/blob/2f0c986dfe525b414b8c57ec9e271cf47ecea516/Src/SAEA.Sockets/Core/Tcp/IocpClientSocket.cs#L188
 
我该如何补抓这个 KernalException?
 
这是我要用 IocpClientSocket 的代码
 https://github.com/cmwong/LearnSuperSocket/blob/master/SocketServer/SAEASocket/EventSocketClient.cs
 
这是测试代码。
 https://github.com/cmwong/LearnSuperSocket/tree/master/SocketServer/testSAEASocket1
